name: flutter_socket_io
description: Flutter Socket IO Plugin
version: 0.4.3
author: ClickApp <ClickTeam@itsclicking.com>
homepage: http://itsclicking.com

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.itsclicking.clickapp.fluttersocketio
    pluginClass: FlutterSocketIoPlugin
